name: ci
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          
      - name: Build Release apk
        run: ./gradlew lintRelease

  build_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
          
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          
      - name: Bump version
        id: bump_version
        uses: oflynned/android-version-bump@master
        with:
          token: ${{secrets.PAT}}
          
      - name: Build Release apk
        run: ./gradlew assembleRelease
        
      - name: Rename release
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/aa-torque.apk

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          name: ${{ steps.bump_version.outputs.new_tag }}
          generate_release_notes: true
          draft: true
          files: |
            app/build/outputs/apk/release/aa-torque.apk

